name: 'multi-arch images build'
 
on:
  workflow_dispatch:
  push:
jobs:
  multiarch-build:
    runs-on: ubuntu-latest
    steps:
      - name: add checkout action...
        uses: actions/checkout@v2
 
      - name: configure QEMU action...
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
 
      - name: configure Docker Buildx...
        id: docker_buildx
        uses: docker/setup-buildx-action@master
 
      - name: login to Quay.io...
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_PUBLISH_ROBOT }}
          password: ${{ secrets.QUAY_PUBLISH_TOKEN }}
 
      - name: build Multi-arch images...
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.docker_buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/ppc64le,linux/arm64,linux/s390x
          push: true
          tags: quay.io/konveyor/builder:latest
